# -*- coding: utf-8 -*-
"""aula01a05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLBSkyZvACRmFkG7OJ-N2ulnqyUIUEoK
"""

import numpy as np

# Contrução manual de arrays

a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a.ndim)
print(len(a))

# Criação de arrays utiliando funções

c=np.arange(0,10,0.1)
print(c)

d=np.linspace(1,5,6)
print(d)

# Arrays comuns
e=np.ones((2,3))
print(e)

f=np.random.rand(2,3)
print(f)

g=np.eye(3)
print(e)

h=np.diag(np.array([1,2,3,4]))
print(h)

# Indexação e cortes (slices) de arrays

a=np.arange(10,21)
print(a)

print(a[2:5])

print(a[:5])

b=np.random.rand(5,5)
print(b)

print(b[0:2,2])

from skimage import io
import matplotlib.pyplot as plt
plt.figure(figsize=(15, 8))
img=io.imread('/content/tecnologia.jpg')

plt.imshow(img)
plt.show()

print(img)

print(img.shape)

nova_img=img[0:410,640:]
plt.figure(figsize=(15, 8))
plt.imshow(nova_img)
plt.show()

# Operações com arrays

# Com escalares


a=np.random.randint(1,20,8)

print(a)

# Entre arrays

b=np.random.randint(1,100,8)
print(b)

m1=np.random.randint(1,10,(3,2))
m2=np.random.randint(1,10,(2,3))

# Multiplicação de matrizes

print(m1)
print(m2)

print(m1.dot(m2))

#  Comparações

a1=np.array([1,2,3,4])
a2=np.array([4,2,2,4])

np.array_equal(a1,a2)

# Métodos importantes e máscaras em arrays

array=np.random.randn(10)
mtx=np.random.randn(5,5)

array.shape

mtx.shape

array

array.min()

array.argmin()

array.sort()
array

# Máscaras

a=np.random.randint(1,10,5)

print(a)

a[[False,True,True,False,False]]

a[a>4]