# -*- coding: utf-8 -*-
"""aula06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_4vtNW7IFIJcfHdIJzwtECoOncIi-UG
"""

#Importação das bibliotecas

import pandas as pd
import numpy as np

# Series

steps=pd.Series([4216,3867,7934,4180,5344])
steps

steps.values

steps=pd.Series(data=[4216,3867,7934,4180,5344],index=['seg','ter','qua','qui','sex'])
steps

steps.describe()