# -*- coding: utf-8 -*-
"""aula07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UuakDF0nq1QNMIoZael0eAd8nEl9YBCv

## Aula 07- Indexações, operações e máscaras
"""

import numpy as np
import pandas as pd

d={'Python':10,'JavaScript':9,'Matlab':7}

series=pd.Series(d)
series

"""## Indexação"""

s=pd.Series(data=np.random.randint(1,5,10),index='A B C D E F G H I j'.split())

s['C':'E']

"""## Máscaras"""

s[s>2]