# -*- coding: utf-8 -*-
"""aula09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G8wzaThcJCaPnSRbzxHrIaZ2LGqJhpkD
"""

import pandas as pd
import numpy as np

df=pd.read_csv('Titanic-Dataset.csv')
df.head(10)

planilha=pd.read_excel('dados.xlsx')
planilha.head(10)

planilha_filtrada=filtro=planilha[(planilha['MUNICIPIO']=='FERRAZ DE VASCONCELOS')|(planilha['MUNICIPIO']=='SUZANO')]
planilha_filtrada