# -*- coding: utf-8 -*-
"""topicosRegressao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lddXQxFAo3dCwPBMaxdNkyzF4ArhV9qp

## Carregando os dados
"""

import pandas as pd

dados=pd.read_csv('dados_exemplo.txt',sep='\t')
print(dados)



"""## Verificando o número de linhas e colunas do dataframe


"""

print(dados.shape)

"""## Criańdo um resumo estatístico"""

dados.describe()

"""## Regressão linear"""

x=dados[['temperatura','dias','pureza','producao']]
y=dados['consumo']

"""## Correlograma"""

df=pd.DataFrame(dados)
df

"""## Importando bibliotecas"""

import seaborn as sns
import matplotlib.pyplot as plt

# Calcular a matriz de correlações

correlation_matrix = df.corr()
correlation_matrix

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix,annot=True,cmap='coolwarm',linewidths=0.5)
plt.title('Correlograma de Matriz de Correlação')
plt.show()

## Criar o painel de scatter plots

sns.pairplot(df)
plt.show()