# -*- coding: utf-8 -*-
"""aula05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LerOX2ZjexZJo7tUByF_UUMzdKL8WOB7
"""

class Dog:
  def __init__(self,name,age):
    self.name=name
    self.age=age

  def sit(self):
    # simula o cachorro atendendo ao comando sentar
    print(f'{self.name} está sentado.')

  def roll_over(self):
    #simula o cachorro atendendo ao comando rolar
    print(f'{self.name} rolou')

dog=Dog('Caramelo',12)
print(f'O nome do meu cachorro é {dog.name}.')
print(f'Meu cachorro tem {dog.age} anos.')

