# -*- coding: utf-8 -*-
"""python-santander.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3i9Y7-VRxO4d_eey5dTAgYWnfjuv-eS
"""

print("Olá mundo!!!")

from google.colab import drive
drive.mount('/content/drive')

"""## if/else/elif"""

nota=75
if nota>=90:
  print("Excelente")
elif nota>=80:
  print("Muito bom")
elif nota>=70:
  print("Bom")
else:
  print("Precisa melhorar")

"""## Listas"""

frutas=['maça','banana','laranja','morango']
for fruta in frutas:
  print(fruta)

"""## While"""

contador=0
while contador<=5:
  print(contador)
  contador+=1

contador=0
while True:
  print (contador)
  contador+=1
  if(contador==11):
    break

"""## For"""

num=7
primo=True
for i in range(2,num):
  if(num%i==0):
    primo=False
    break

if (primo==False or num==1):
  print("Não é primo")
else:
  print("É primo")

num=10
for i in range(2,num):
  print(i)

"""## Continue

"""

for i in range(10):
  if(i%2==0):
    continue
  print(i)

"""## Pass

"""

for i in range(10):
  pass

"""## Listas/Criação e acesso"""

frutas=["maça","banana","Laranja"]
print(frutas[0])
print(frutas[1])
print(frutas[2])

frutas=["maça","banana","Laranja"]
print(frutas[-1])
print(frutas[-2])
print(frutas[-3])

"""## Métodos de listas






"""

frutas=["maça","banana","laranja"]
frutas.append("pera")
print(frutas)

frutas.insert(1,"uva")
frutas.remove("banana")
print(frutas)

fruta_removida=frutas.pop(2)
print(frutas)
print(fruta_removida)

frutas.sort()
print(frutas)

frutas.reverse()
print(frutas)

"""##Listas de Compreensão

"""

numeros=[1,2,3,4,5]
quadrados=[x**2 for x in numeros if x%2==0]
print(quadrados)

"""## Tuplas
# Criação e acesso

"""

minha_tupla=(1,3,2,4,2)
print(len(minha_tupla))

print(minha_tupla.index(4))

print(minha_tupla.count(3))

"""## Dicionários
# Criação/Acesso/Métodos

"""

pessoa={"nome":"José","idade":25,"cidade":"Madri"}
print(pessoa["nome"])
print(pessoa["idade"])
print(pessoa["cidade"])

print(pessoa.keys())
print(pessoa.values())
print(pessoa.items())

pessoa.update({"profissão":"Engenheiro"})
print(pessoa)

"""## Conjuntos


"""

frutas={"maça","banana","laranja"}
numeros=set([1,2,3,4,5])

A={1,2,3}
B={3,4,5}

uniao=A|B
print(uniao)

intersecao=A&B
print(intersecao)

diferenca=A-B
print(diferenca)

diferenca_simetrica=A^B
print(diferenca_simetrica)

"""## Métodos

"""

frutas.add("pera")
print(frutas)

frutas.remove("banana")
print(frutas)

frutas.discard("uva")
print(frutas)

frutas.clear()
print(frutas)

"""## Funções
#Definição e chamada de funções

"""

def saudacao():
  print("Olá mundo!!!")

saudacao()

"""##Parâmetros e argumentos


"""

def saudacao(nome):
  print(f"Olá, {nome}!!!")

saudacao("João")
saudacao("Maria")

"""##Valores de retorno"""

def soma(a,b):
  return a+b

print(soma(2.5,4.3))

"""## Funções anônimas


"""

quadrados=lambda x:x**2

print(quadrados(5))

"""## Erros comuns

Erro de sintaxe (sintaxError)
"""

def minha_funcao(): #ocorre quando faltam os dois pontos
  print("Olá")

""" Erro de nome (nameError)"""

print(variavel_nao_definida) #Ocorre quando se faz referência a uma variável ou função que não foi definida

"""Erro de tipo (typeError)"""

resultado=5+"10"  #Ocorre quando se realiza uma operação com tipos de dados incompatíveis, como tentar somar um número a uma string
print(resultado)

"""Erro de índice (indexError)"""

lista=[1,2,3,4]
print(lista[4])  #o índice está fora do intervalo

"""## Manejo de excessões

try
"""

try:
  #Código que pode gerar uma excessão
  resultado=10/0
  print(resultado)
except ZeroDivisionError:
    print("Erro: divisão por zero.")

"""except"""

try:
  resultado=10/0
  print(resultado)
except ZeroDivisionError:
  print("Erro: divisão por zero")
except ValueError:
  print("Erro: valor inválido")

"""# Entradas e saídas"""

nome=input('Digite seu nome: ')
idade=int(input('Digite sua idade: '))
print(f'Olá, {nome}! Você tem {idade} anos.')

"""#Saída de dados"""

nome="Juan"
idade=25
print("Olá, meu nome é {} e tenho {} anos.".format(nome,idade))

"""## Leitura e escrita de arquivos"""

arquivo=open("dados.txt","w")
arquivo.write("Olá mundo!!!")
arquivo.close()

with open ("dados.txt","r") as arquivo:
  conteudo=arquivo.read()
  print(conteudo)
  arquivo.close()

"""## Importação e criação de módulos

# Importação de módulos
"""

import math
resultado=math.sqrt(25)
print(resultado)

"""# Funções e classes de módulos padrões"""

import random
import datetime
numero_aleatorio=random.randint(1,10)
print(numero_aleatorio)

data_atual=datetime.datetime.now()
print(data_atual)



