# -*- coding: utf-8 -*-
"""aula08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLNddd8lFJPUYhYcHvzIvJT48h5fZWLO
"""

import numpy as np
import pandas as pd

dados=np.array([[72,160,26],[80,170,19],[60,165,15]])
dados

df=pd.DataFrame(data=dados,columns=['Peso','Altura','Idade'])
df

## indexação

df['Altura']

df.loc[2]

df.loc[0]['Altura']

df.iloc[2][1]