# -*- coding: utf-8 -*-
"""conceitosEstR.r

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WLFtSxPo6Ro4ESoTCxKqFCwUxoNPQjR4

## Vetores
"""

peso<-c(60.5,70,69.8,101,20)
peso

"""## Factor"""

r<-c('pial','comercial','pial','comercial','pial','comercial','pial','comercial')
r<-factor(r)
r

"""## Matriz"""

producao<-matrix(c(10,14,9,23,42,11,23,54),2,4,byrow=T)
producao

"""## Listas"""

estudante<-list(matricula=34453,nome='Zezinho',notas=c(20,15,40))
estudante

estudante[[2]]



"""## DataFrames"""

notas.inform<-data.frame(mat=c(2355,3456,2334,5456),turma=c('t1','t2','t3','t4'),notas=c(10.3,9.3,14.2,15))
notas.inform

"""## Vetor índice"""

x<-c(-20,3,-4,35,50)
x>0

"""## Leitura de dados no R"""

df<-read.csv('/content/Iris.csv')
df

"""## Medidas de posição"""

v1<-iris$Sepal.Length
media<-mean(v1)
media

variancia<-var(v1)
variancia

desviopadrao<-sd(v1)
desviopadrao

dados<-iris[,-5] #-5 exclui a quinta coluna
dados

vetorMedias<-colMeans(dados)
vetorMedias

mCovariancias<-var(dados)
mCovariancias

mCorrelacoes<-cor(dados)
mCorrelacoes

pl<-iris$Petal.Length
pw<-iris$Petal.Width

plot(pl,pw)

"""## Diagrama de dispersão"""

plot(dados)