# -*- coding: utf-8 -*-
"""medidasdePosDisperAssoc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuAPLQTun2NMPfTkgXt0OcOHd0LmfGky
"""

import pandas as pd
import numpy as np

dados=np.array([[7,3,9],[4,6,11],[4,2,5],[5,5,7]])
df=pd.DataFrame(dados,index=['a','b','c','d'],columns=['x','y','z'])
df

means_values=df.mean()
means_values

var_values=df.var()
var_values

cov=df.cov()
cov

corr=df.corr()
corr