# -*- coding: utf-8 -*-
"""medidasdePosDisperAssoc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuAPLQTun2NMPfTkgXt0OcOHd0LmfGky
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import datasets
# %matplotlib inline

dados=np.array([[7,3,9],[4,6,11],[4,2,5],[5,5,7]])
df=pd.DataFrame(dados,index=['a','b','c','d'],columns=['x','y','z'])
df

means_values=df.mean()
means_values

var_values=df.var()
var_values

cov=df.cov()
cov

corr=df.corr()
corr

pd.plotting.scatter_matrix(df[['x','y','z']])
plt.show()

data=[[42,2],[52,3],[48,2],[58,3]]
columns=['Valor da nota','Número de livros']

df_livros=pd.DataFrame(data,columns=columns)
df_livros

#Vetor de médias
means_values=df_livros.mean()
means_values

#Matriz de covariâncias
cov=df_livros.cov()
cov

#Matriz de correlações
corr=df_livros.corr()
corr

sns.pairplot(df_livros)
plt.show() # Para exibir o gráfico