# -*- coding: utf-8 -*-
"""CDPO1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtST0dKUrEWkZnzQHm4kxwtLJCRhGBsY
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# %matplotlib inline

# Modifique o caminho se necessário para fazer a leitura dos dados
url = "https://raw.githubusercontent.com/cibelerusso/Datasets/refs/heads/main/DadoseDecisoes.csv"

# Dados banco - Leitura dos dados
dados = pd.read_csv(url)

dados

dados.columns

# Cálculo das medidas descritivas, média, mediana e moda

mean=dados['Salário'].mean()
median=dados['Salário'].median()
mode=dados['Salário'].mode().values[0]


# Aqui criamos as "molduras" (ax_box e ax_hist)
f, (ax_box, ax_hist) = plt.subplots(2, sharex=True, gridspec_kw={"height_ratios": (.15, .85)})


#Gráfico de caixa ou boxplot com medidas descritivas indicadas
sns.boxplot(data=dados,x='Salário',ax=ax_box)
ax_box.axvline(mean,color='r',linestyle='--',label='Média')
ax_box.axvline(median,color='g',linestyle='-',label='Mediana')
ax_box.axvline(mode,color='b',linestyle='-',label='Moda')

# Histograma com medidas descritivas indicadas
sns.histplot(data=dados,x='Salário',ax=ax_hist,kde=True)
ax_hist.axvline(mean,color='r',linestyle='--',label='Média')
ax_hist.axvline(median,color='g',linestyle='-',label='Mediana')
ax_hist.axvline(mode,color='b',linestyle='-',label='Moda')

plt.legend()
plt.show()

mediana_salario=dados['Salário'].median()

nivelSalario=lambda x:'Alto' if x>=median else 'Baixo'

# Criar variável binária nivelSalario (0 para salário abaixo do valor de corte, 1 para salários acima)

dados['nivelSalário']=dados['Salário'].apply(nivelSalario)

dados.head()

# Estatísticas descritivas para variáveis quantitativas

np.round(dados.describe(),2)

dados.groupby(by='Gênero')['Salário'].mean()

# Associação de variáveis com salário: depende dos tipos de variáveis

plt.figure(figsize=(10, 6))
sns.boxplot(x=dados['nivelSalário'],y=dados['Produtividade'],hue=dados['Gênero'],palette='Set2')

plt.figure(figsize=(12, 6))
sns.boxplot(x=dados['nivelSalário'],y=dados['Satisfação'],hue=dados['Gênero'],palette='Set2')

# Associação entre duas variáves qualitativas

# Tabela de contigência

tabela_dupla=pd.crosstab(dados['nivelSalário'],dados['Gênero'],normalize='index')
tabela_dupla

tabela_dupla.plot.barh()

tabela_dupla=pd.crosstab(index=[dados['Departamento'],dados['Gênero']],columns=dados['nivelSalário'],normalize='index')
tabela_dupla

tabela_dupla.plot.barh(stacked="True")
plt.legend(title="Salário")
plt.show()

# Gráfico mosaico


from statsmodels.graphics.mosaicplot import mosaic

plt.rcParams['figure.figsize'] = (10, 6)
mosaic(dados, ['Departamento', 'nivelSalário'])

# Adicionar rótulos e títulos
plt.title('Distribuição de salários por departamento')
plt.xlabel('Departamento')
plt.ylabel('Salário')

plt.show()

## Associação entre variáveis quantitativas

plt.figure(figsize=(10,6))
sns.scatterplot(data=dados,x='Produtividade',y='Satisfação',hue='Gênero',alpha=1)

