# -*- coding: utf-8 -*-
"""Imersao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGe4ufddDtsJdaxym1alenTYZ8T31FvE

## Aula01 - Explorando dados com pandas
"""

import pandas as pd

ur="https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv"

df=pd.read_csv(ur)

df.head()

df.info()

df.describe()

df.shape

linhas, colunas = df.shape[0],df.shape[1]
print(f"O dataframe possui {linhas} linhas e {colunas} colunas")

df.columns

df.columns = [
    'ano',
    'senioridade',
    'contrato',
    'cargo',
    'salario',
    'moeda',
    'usd',
    'residencia',
    'remoto',
    'empresa',
    'tamanho_empresa'
]
df.head()

df['remoto'].value_counts()

df['tamanho_empresa'].value_counts()

df['senioridade'] = df['senioridade'].replace({
    'EN': 'Júnior',
    'MI': 'Pleno',
    'SE': 'Sênior',
    'EX': 'Executivo'
})
df['senioridade'].value_counts()

df['contrato'] = df['contrato'].replace({
    'FT': 'Tempo Integral',
    'PT': 'Tempo Parcial',
    'CT': 'Contrato',
    'FL': 'Freelancer'
})
df['contrato'].value_counts()

df['tamanho_empresa'] = df['tamanho_empresa'].replace({
    'S': 'Pequena',
    'M': 'Média',
    'L': 'Grande'
})
df['tamanho_empresa'].value_counts()

df['remoto'] = df['remoto'].replace({
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
})
df['remoto'].value_counts()

df.head()

df.describe(include='object')

"""## Aula 02 - Aprenda a limpar e preparar os dados"""

df.isnull().sum()

df['ano'].unique()

df[df.isnull().any(axis=1)]

import numpy as np

df_salarios=pd.DataFrame({'Nome':['Ana','Bruno','Carlos','Daniele','Val'],'Salário':[4000,np.nan,5000,np.nan,100000]})

df_salarios

df_salarios['Salário'] = df_salarios['Salário'].fillna(df_salarios['Salário'].median())
df_salarios

df_temperaturas=pd.DataFrame({'Dia':['seg','ter','quar','quin','sex'],'Temperatura':[30,np.nan,np.nan,28,27]})
df_temperaturas

df_temperaturas['Temperatura'] = df_temperaturas['Temperatura'].bfill()
df_temperaturas

df_cidades=pd.DataFrame({'Nome':['Ana','Bruno','Carlos','Daniele','Val'],'Cidade':['São Paulo',np.nan,'Belo Horizonte',np.nan,'Rio de Janeiro']})
df_cidades

df_cidades['Cidade']=df_cidades['Cidade'].fillna("Não informado")
df_cidades

df.isnull().sum()

df.dropna(inplace=True)
df.isnull().sum()

df['ano']=df['ano'].astype('int64')
df

"""## Aula 03 - Crie gráficos e conte histórias com Dados"""

df['senioridade'].value_counts().plot(kind='bar',title='Distribuição de senioridade')

import seaborn as sns

sns.barplot(data=df,x='senioridade',y='usd' )

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.barplot(data=df,x='senioridade',y='usd' )
plt.title('Salário médio por senioridade')
plt.xlabel('Senioridade')
plt.ylabel('Salário médio anual')
plt.show()

ordem=df.groupby('senioridade')['usd'].mean().sort_values(ascending=True).index
ordem

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.barplot(data=df,x='senioridade',y='usd' ,order=ordem)
plt.title('Salário médio por senioridade')
plt.xlabel('Senioridade')
plt.ylabel('Salário médio anual')
plt.show()

plt.figure(figsize=(10,5))
sns.histplot(df['usd'],bins=50,kde=True)
plt.title('Distribuição dos salários anuais')
plt.xlabel('Salário')
plt.ylabel('Frequência')
plt.show()

plt.figure(figsize=(10,5))
sns.boxplot(x=df['usd'])
plt.title('Distribuição dos salários anuais')
plt.xlabel('Salário')
plt.show()

ordem_senioridade=['júnior','pleno','sênior','executivo']

plt.figure(figsize=(8,5))
sns.boxplot(x='senioridade',y='usd',data=df,order=ordem,palette='Set2',hue='senioridade')
plt.title('Distribuição salarial por nível de experiência')
plt.xlabel('Senioridade')
plt.show()

import plotly.express as px
df_avg_salary = df.groupby('senioridade')['usd'].mean().reset_index()
fig = px.bar(
    df_avg_salary,
    x='senioridade',
    y='usd',
    title='Média Salarial por Senioridade',
    labels={'senioridade': 'Senioridade', 'usd': 'Salário Médio Anual (USD)'},
    category_orders={'senioridade': ordem}
)
fig.show()

remoto_contagem=df['remoto'].value_counts().reset_index()
remoto_contagem.columns=['tipo_trabalho','quantidade']

fig = px.pie(
    remoto_contagem,
    names='tipo_trabalho',
    values='quantidade',
    title='Proporção dos tipos de trabalho',
    hole=0.5

)
fig.update_traces(textinfo='percent+label')
fig.show()