# -*- coding: utf-8 -*-
"""introdução.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qTZ_K4Fehtn4MvtvmocCm7BVLr4pmDmz

## Aula01
"""

print(" I competição de programação da Start")

ano="II"

print(ano,"Competição de programação da Start")

print(f'{ano} Competição de programação da Start')

"""## Desafio - aula01"""

ano='II'
local='Anhembi/São Paulo'
tema='Robótica'
print(f'{ano} Competição de Programação da Start.Local: {local}, tema:{tema}.')

"""## Aula02"""

ficcao=10
nao_ficcao=8
infantil=6
pontos_rodrigo=ficcao+nao_ficcao+infantil
print(f'Os pontos totais do Rodrigo são: {pontos_rodrigo}')

"""## Desafio - aula02"""

ficcao=10
nao_ficcao=8
infantil=6
pontos_rodrigo=ficcao+nao_ficcao+infantil
pontos_ana=2*ficcao+5*infantil
pontos_acumulados=pontos_rodrigo+pontos_ana
print(f'Os pontos totais do Rodrigo são: {pontos_rodrigo}')
print(f'Os pontos totais da Ana são: {pontos_ana}')
print(f'OS pontos acumulados por Rodrigo e Ana foram: {pontos_acumulados}')

"""## Aula 03"""

total_figurinhas=int(input('Digite o total de figurinhas: '))
numero_amigos=int(input('Digite o número de amigos: '))
figurinhas_amigos=total_figurinhas//(numero_amigos+2)
figurinhas_joao=2*figurinhas_amigos


print( f'João recebeu {figurinhas_joao} figurinhas.')

"""## Desafio - aula03

"""

total_figurinhas=int(input('Digite o total de figurinhas: '))
numero_amigos=int(input('Digite o número de amigos: '))
figurinhas_amigos=total_figurinhas//(numero_amigos+2)
figurinhas_joao=2*figurinhas_amigos


figurinhas_extras=int(input('Total de figurinhas extras: '))
figurinhas_extras_amigos=figurinhas_extras//(numero_amigos+2)
figurinhas_extras_joao=2*figurinhas_extras_amigos


print( f'João recebeu {figurinhas_joao} figurinhas. Além disso ele recebeu mais {figurinhas_extras_joao} figurinha extras. Totalizando {figurinhas_joao+figurinhas_extras_joao} figurinhas.')

"""## Aula 04"""

numero_alunos=int(input('Digite a quantidade de alunos: '))
numero_monitores=int(input('Digite o número de monitores: '))
resposta_positiva='Pode ir'
resposta_negativa='Não pode ir'
if numero_alunos+numero_monitores <=50:
  print(resposta_positiva)
else:
  print(resposta_negativa)

"""## Desafio - aula 04"""

numero_alunos=int(input('Digite a quantidade de alunos: '))
numero_monitores=int(input('Digite o número de monitores: '))
resposta_positiva='Pode ir'
resposta_negativa='Não pode ir'
numero_professores=8
if numero_alunos+numero_monitores+numero_professores <=30:
  print(resposta_positiva)
else:
  print(resposta_negativa)

"""## Aula 05"""

p=int(input('Digite a posição da porta P (0 ou 1): '))
if p==0:
  print('Bolinha irá para o caminho C')
else:
  r=int(input('Digite a posição da porta R (0 ou 1): '))
  if r==0:
    print('Bolinha irá para o caminho B')
  else:
    print( 'Bolinha irá para o caminho A')

"""## Desafio - aula 05"""

p=int(input('Digite a posição da porta P (0 ou 1): '))
if p==0:
  print('Bolinha irá para o caminho C')
else:
  r=int(input('Digite a posição da porta R (0 ou 1): '))
  if r==0:
    print('Bolinha irá para o caminho B')
  else:
    q=int(input('Digite a posição da porta Q (0 ou 1): '))
    if q==0:
      print('Bolinha irá para o caminho A')
    else:
      print( 'Bolinha irá para o caminho D')

"""## Aula 06"""

def calcula_idade_maior(idade_monica,idade_filho1,idade_filho2):
  idade_filho3=idade_monica-idade_filho1-idade_filho2
  idade_max=max(idade_filho1,idade_filho2,idade_filho3)
  return idade_filho3,idade_max

calcula_idade_maior(68,12,30)

"""## Desafio - Aula 06"""

def quantidade_maxima(l1,l2,l3,l4,l5):
  quantidade_max=max(l1,l2,l3,l4,l5)
  return quantidade_max


quantidade_maxima(24,100,45,30,23)

"""## Aula 07"""

def calcula_tabuada(numero):
  for valor in range(1,11):
    print(f'{numero} X {valor} = {numero*valor}')

calcula_tabuada(5)



"""## Desafio Aula 07"""

def calcula_soma(numero):
  for valor in range(1,11):
    print(f'{numero} + {valor} = {numero+valor}')

calcula_soma(5)

"""## Desafio final - Dado um número inteiro não negativo na base dez, converta para base 2."""

num = int(input('Digite um inteiro não negativo: '))
if num == 0:
    print([0])
else:
    binario = []
    while num > 0:
        resto = num % 2
        binario.append(str(resto))  # Convertendo o resto para string
        num = num // 2
    binario.reverse()
    binario=''.join(binario)
    print(binario)