# -*- coding: utf-8 -*-
"""primeirospassos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHNFxDTiGlTpJD8zWfSFqBENLBn8mu-i

## Primeiros passos em Python  para Dados
"""

print('Boas vindas a aula de Python')

nome='Washington Fernandes de Barros'
print(nome)

cor_favorita='azul'
print(f'Minha cor favorita é {cor_favorita}.')

saldo =5000.00

print(f'Saldo atual R$ {saldo}')

import this

idade=18
if idade >=18:
    print(f'Com {idade} anos você pode dirigir.')
else:
    print(f'Com {idade} anos você não pode dirigir.')