# -*- coding: utf-8 -*-
"""aula10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DEmTSKSl1BY9pBydemz0eRPl8WLio82h

## Analisando e filtrando dados
"""

import numpy as np
import pandas as pd

df=pd.read_csv('Titanic-Dataset.csv')
df.head()

df.columns #permite a visualização dos labels das colunas

df.index #permite a visualização dos índices das linhas

df['Sex'].unique() #permite a visualização dos valores únicos de uma coluna

df['Age'].unique() #permite a visualização dos valores únicos de uma coluna

df['Sex'].value_counts() #permite a visualização da contagem de valores únicos de uma coluna

df['Age'].value_counts() #permite a visualização da contagem de valores únicos de uma coluna

df['Age'].mean() #permite a visualização da média dos valores de uma coluna

df['Age'].median()

df.describe()

df.duplicated().sum() #permite a visualização da contagem de valores duplicados

df.drop_duplicates() #permite a remoção de valores duplicados

"""## Filtragem de dados"""

df['Age']>25 #permite a visualização de valores booleanos de uma coluna

df[df['Age']>25] #permite a visualização de linhas que atendem a uma condição

df[df['Age']>df['Age'].mean()] #permite a visualização de linhas que atendem a uma condição

df[df['Sex']=='female'] #permite a visualização de linhas que atendem a uma condição