# -*- coding: utf-8 -*-
"""aula06 - parte3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKRHbCY7w_3I6WdmxEtd6IRwRdmHe-dE
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

# Carregando a base de dados

df=pd.read_csv('Bases de dados - Limpeza e tratamento.csv')
df.head(10)

#Padronizando os dados da coluna Pagamento

df['Pagamento']='Cartão de Crédito'
df.head(10)

#Limpeza de dados

#Apagando todos os nulos da coluna idade

df=df.dropna(subset=['Idade'])
df.head(10)

# Convertendo os dados da coluna Idade para o tipo inteiro

df['Idade']=df['Idade'].round().astype(int)
df.head(10)

#Convertendo a coluna Data_Compra para datetime

df['Data_Compra']=pd.to_datetime(df['Data_Compra'])
df.head(10)

# Alterando os dados negativos da coluna Valor_Compra

df['Valor_Compra']=df['Valor_Compra'].abs()
df.head(10)

# Removendo os dados nulos da coluna Valor_Compra

df=df.dropna(subset=['Valor_Compra'])
df.head(10)

#Removendo valores duplicados

df=df.drop_duplicates()
df.head(10)

# Agrupando os dados por data e somando os valores das vendas

df_agrupado=df.groupby('Data_Compra')['Valor_Compra'].sum().reset_index()
df_agrupado.head(10)

#Criando gráfico de linhas

plt.figure(figsize=(10,6))
plt.plot(df_agrupado['Data_Compra'],df_agrupado['Valor_Compra'],marker='o',linestyle='-',color='b')

# Adicionando títulos e rótulos

plt.title('Vendas por Período')
plt.xlabel('Data da Compra')
plt.ylabel('Valor da Compra')

#Exibindo o gráfico

plt.grid(True)
plt.xticks(rotation=45)
plt.yticks(rotation=45)
plt.show()

#   Agrupando os dados por produto e somando os valores da vendas

df_agrupado=df.groupby('Produto')['Valor_Compra'].sum().reset_index()
df_agrupado.head()

# Criando o gráfico de barras

plt.figure(figsize=(10,6))
bars=plt.bar(df_agrupado['Produto'],df_agrupado['Valor_Compra'],color='skyblue')

# Adicionando os valores no topo de cada barra

for bar in bars:
  yval=bar.get_height()
  plt.text(bar.get_x()+bar.get_width()/2,yval,round(yval,2),ha='center',va='bottom')
# Adicionando títulos e rótulos

plt.title('Vendas por Produto')
plt.xlabel('Produto')
plt.ylabel('Valor das Vendas')

# Exibindo o gráfico

plt.show()