# -*- coding: utf-8 -*-
"""aula06-parte2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chkinXpSStLzEQ2DP-wSI5LHShVcw7uK
"""

import pandas as pd
import seaborn as sns

iris=sns.load_dataset('iris')
iris.to_csv('iris.csv',index='False')

dsf_csv=pd.read_csv('iris.csv')

#10 linhas do dataframe df_csv

print(dsf_csv.head(10))

"""## Organização de dados"""

import pandas as pd
prices=pd.read_csv('prices.csv',decimal=',')
items=pd.read_csv('items.csv')

table_final=items.merge(prices,on='item_id')
print(table_final)

import pandas as pd

items=pd.read_csv('items.csv',decimal=',')
new_products=pd.read_csv('new_products.csv',decimal=',')

products=pd.concat([items,new_products],ignore_index=True)
print(products)

"""## Limpeza e preparação dos dados"""

import pandas as pd

df=pd.read_csv('Bases de dados.csv')
df.head(10)

df['Pagamento']='Cartão de Crédito'
df.head(10)

#Apagar todos os nulos
df=df.dropna(subset=['Idade'])
df.head(10)

import pandas as pd

df=pd.read_csv('Bases de dados.csv')
df.head(10)

# Fazer uma média das idades dos compadores

media_idades=df['Idade'].mean()
df['Idade']=df['Idade'].fillna(media_idades)
df.head(10)

df['Idade']=df['Idade'].round().astype(int)
df.head(10)

df['Valor_Compra']=df['Valor_Compra'].abs()
df.head(10)

df['Pagamento']=df['Pagamento'].str.upper()
df

# Apagar duplicatas
df=df.drop_duplicates()
df

df.loc[df['ID_Cliente']==12,'Valor_Compra']=230
df.loc[df['ID_Cliente']==6,'Valor_Compra']=75
df.loc[df['ID_Cliente']==15,'Valor_Compra']=560
df