# -*- coding: utf-8 -*-
"""aula04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Swyr6SJMCsrj3cdrA5ScS2zJPFwZV0Kq

## Funções
"""

def greet_user():
  # Imprime saudação na tela
  print('Olá')

print("Chamando a função greet_user()...")
greet_user()

def describe_pet(animal_type,pet_name):
  print(f'\nEu tenho um {animal_type}.')
  print(f'Meu {animal_type} se chama {pet_name.title()}')

#Chamando a função describe_pet()...
describe_pet('hamster','kiko')

def repeat(mytext,text_length):
  s=''
  for i in range(text_length):
    s+=mytext
  return s

#Chamada da função
output=repeat('->',20)
print(output)

#definição da função
def myfunc():
  x='fantástico'
  print('Escopo local...')
  print('Python é '+x)


#programa principal
x='impressionante'
myfunc()
print('\nEscopo global...')
print("Python é "+x)