# -*- coding: utf-8 -*-
"""aula06-parte1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4VXltoiEhPwekfb7i_Q7DgbgiUzb_zB

##Tuplas
"""

tupla=('Inteligência','Artificial','e','Computacional')


for elemento in tupla:
  print(elemento)

"""##Listas"""

lista=[1,2,3,"casa",None]
gerador=range(10)
lista_gerador=list(gerador)
print(lista_gerador)

seq=[7,2,3,7,5,6,0,1]
print(seq[1:5])

"""## Dicionários"""

dados_pessoais={'Nome':'Washington',"idade":44,'cidade':'São Paulo'}


dados_pessoais['email']='w_as@yahoo.com'

for chave,valor in dados_pessoais.items():
  print(f'{chave}:{valor}')