# -*- coding: utf-8 -*-
"""aula03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtIpKTQTm2pwtAnFr7peClK5eValZRso
"""

import numpy as np

idades=np.zeros(5,dtype=int)

print('idades',idades)

contador=np.array([4,3,2,1])

print("contador = ",contador)

n=int(input('Informe o número de elementos: '))
A=np.empty(n) #cria um arranjo

# ler do teclado
for i in range(n):
  A[i]=float(input('Informe o %d elemento: '%(i+1)))

#multiplica o vetor por 3
for i in range(n):
  A[i]*=3

# escreve na tela com formatação
print('Imprimindo vetor na tela...')
for i in range(n):
  print('%5.2f' %A[i], end=' ')
print()

a='Diga Olá!!!'

print('Caracter de índice 1...')
print(a[0]) #acessa o elemento de índce 0 da string

#percorre os elementos da string um por um
print('Imprime string...')
for x in a:
  print(x,end='')
print('\n')

#percorre os elementos da string um por um
print('Imprime string...')
for i in range(len(a)):
  print(a[i],end='')

import numpy as np

#matrizes
nl=int(input('Informe o número de linhas : '))
nc=int(input('Informe o número de colunas: '))

#cria matriz
A=np.empty((nl,nc))

for i in range (nl):
  for j in range (nc):
    s='Informe o elemento A[%d][%d]: '%(i,j)
    A[i][j]=float(input(s))

print('Imprime matriz...')
for i in range (nl):
  for j in range (nc):
    print('%5.1f'%A[i][j],end='')
  print()#quebra de linha